### PR TITLE
Make About page data-driven

### PR DESCRIPTION
**Pull request by BobWalsh**

### CODE REVIEW

**Comment by jakelumetta** [comment]
Wouldn't this also require a change to the config file to pull in data for the About page?  https://github.com/ButterCMS/gridsome-starter-buttercms/blob/master/gridsome.config.js#L14

**Comment by BobWalsh** [comment]
It does - I forgot the `pages: about_page'` setting when I cherry-picked this out so that the authToken was not a real value.

**Comment by jakelumetta** [comment]
Thanks @BobWalsh  - looks like there a merge conflict in the gridsome.config.js file.  Can you resolve and then I think this should be good to go.

**Comment by BobWalsh** [comment]
Fixed!

**Pull request closed without merging**
